Match User zntdeploy
    AuthorizedKeysFile /etc/ssh/authorized_keys/zntdeploy
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PubkeyAuthentication yes
    ForceCommand /usr/local/bin/znt-deploy-ssh
    DisableForwarding yes
    PermitTTY no
    PermitUserRC no

Match all

Match User zntcontent
    AuthorizedKeysFile /etc/ssh/authorized_keys/zntcontent
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PubkeyAuthentication yes
    ForceCommand /usr/local/bin/znt-content-ssh
    DisableForwarding yes
    PermitTTY no
    PermitUserRC no

Match all
